"""Add a role column

Revision ID: 22ccf3ceaa5a
Revises: 34404b3654cd
Create Date: 2024-06-14 08:45:05.307437

"""
from typing import Sequence, Union
from datetime import datetime

from alembic import op
import sqlalchemy as sa

from app.constants.env import ADMIN_EMAIL, ADMIN_PASSWORD
from app.utils.password_hash import get_password_hash

from app.models.users import User, Role


# revision identifiers, used by Alembic.
revision: str = '22ccf3ceaa5a'
down_revision: Union[str, None] = '34404b3654cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Enum('ADMIN', 'USER', name='role'), nullable=True))
    # ### end Alembic commands ###

    seed_data()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def seed_data() -> None:
     op.bulk_insert(User.__table__,
        [
           {
            "name": "Admin", 
            "email":ADMIN_EMAIL, 
            "hashed_password": get_password_hash(ADMIN_PASSWORD), 
            "role": Role.ADMIN,
            "is_active": True,
            "created_at": datetime.now(),
           }
        ]
    )